### General project setup
---
 general:
    pipeline: "sap-cloud-sdk" 
    buildTool: "mta"
 stages:
    Build:
       mavenExecuteStaticCodeChecks: false
       npmExecuteLint: false
    Additional Unit Tests:
       npmExecuteScripts: false
       karmaExecuteTests: false
    Release:
       cloudFoundryDeploy: true
       tmsUpload: false
 steps:
    cloudFoundryDeploy:
       cloudFoundry:
        org: '9a5f3a84trial_dev-ccvcd28s'
        space: 'dev'
        credentialsId: 'cf'        
       mtaDeployParameters: "-f --version-rule ALL"    
    artifactPrepareVersion:
       versioningType: "cloud_noTag"   